/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout/analytics'
import { Route as LayoutAnomaliesRouteImport } from './routes/_layout/anomalies'
import { Route as LayoutHistoryRouteImport } from './routes/_layout/history'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAnomaliesRoute = LayoutAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/anomalies': typeof LayoutAnomaliesRoute
  '/history': typeof LayoutHistoryRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof LayoutAnalyticsRoute
  '/anomalies': typeof LayoutAnomaliesRoute
  '/history': typeof LayoutHistoryRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/anomalies': typeof LayoutAnomaliesRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics' | '/anomalies' | '/history' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/analytics' | '/anomalies' | '/history' | '/settings' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/analytics'
    | '/_layout/anomalies'
    | '/_layout/history'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/anomalies': {
      id: '/_layout/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof LayoutAnomaliesRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutAnomaliesRoute: typeof LayoutAnomaliesRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutAnomaliesRoute: LayoutAnomaliesRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
